enableGlobalCache: false

enableImmutableInstalls: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  e7f3:
    npmAuthToken: "${GITHUB_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"
